/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: 8
 *
*   - @qvac/sdk/llamacpp-completion/plugin
*   - @qvac/sdk/llamacpp-embedding/plugin
*   - @qvac/sdk/whispercpp-transcription/plugin
*   - @qvac/sdk/parakeet-transcription/plugin
*   - @qvac/sdk/nmtcpp-translation/plugin
*   - @qvac/sdk/tts-ggml/plugin
*   - @qvac/sdk/onnx-ocr/plugin
*   - @qvac/sdk/sdcpp-generation/plugin
 */

import { initializeWorkerCore, ensureRPCSetup } from "@qvac/sdk/worker-core";
import { registerPlugin } from "@qvac/sdk/plugins";
import { getServerLogger } from "@qvac/sdk/logging";

import { llmPlugin } from "@qvac/sdk/llamacpp-completion/plugin";
import { embeddingsPlugin } from "@qvac/sdk/llamacpp-embedding/plugin";
import { whisperPlugin } from "@qvac/sdk/whispercpp-transcription/plugin";
import { parakeetPlugin } from "@qvac/sdk/parakeet-transcription/plugin";
import { nmtPlugin } from "@qvac/sdk/nmtcpp-translation/plugin";
import { ttsPlugin } from "@qvac/sdk/tts-ggml/plugin";
import { ocrPlugin } from "@qvac/sdk/onnx-ocr/plugin";
import { diffusionPlugin } from "@qvac/sdk/sdcpp-generation/plugin";

const { hasRPCConfig } = initializeWorkerCore();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 8");

registerPlugin(llmPlugin);
registerPlugin(embeddingsPlugin);
registerPlugin(whisperPlugin);
registerPlugin(parakeetPlugin);
registerPlugin(nmtPlugin);
registerPlugin(ttsPlugin);
registerPlugin(ocrPlugin);
registerPlugin(diffusionPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
